steps:
  # 1) Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-service:${SHORT_SHA}'
      - '.'

  # 2) Push the Docker image to GCR (or Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/my-service:${SHORT_SHA}'

  # 3) Deploy to Cloud Run (this also uses "gcloud" to do the deployment)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-service:${SHORT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'    # or your preferred region
      - '--allow-unauthenticated'  # if you want it publicly accessible
