name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} -f docker/Dockerfile .

      - name: Save Docker image to file
        run: |
          docker save myapp:${{ github.sha }} -o myapp-${{ github.sha }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-image-${{ github.sha }}
          path: myapp-${{ github.sha }}.tar

